### PR TITLE
formats 'Get chain information' example in-line with others

### PR DESCRIPTION
**Pull request by benjichat**
Updates example in the API documentation so that it:

(1) works
(2) is the same formatting as others in the documentation.

### CODE REVIEW

**Review by jacogr — APPROVED** [review]

**Comment by jacogr** [comment]
Thank you fort this!

**Comment by benjichat** [comment]
> Thank you for this!

No problems. This will not be the first PR I make. 

Must one make a PR for contributors also OR is that updated by the team?

**Comment by benjichat** [comment]
> Thank you for this!

It won't be my first!

**Comment by benjichat** [comment]
> Thank you for this!

You're welcome. It won't be my last.

**Pull request merged**
