### PR TITLE
Add search plugin

### PR DESCRIPTION
**Pull request by SaltyCucumber**
I've added local search plugin, doesn't require any third party to work.

Screenshot 2022-06-16 at 17 46 58

styles were updated with !important tag according to recommendation in https://github.com/cmfcmf/docusaurus-search-local/issues/107#issuecomment-1119831938

P.S. Do we want to use full fledged Algolia DocSearch? Will require a registration https://docsearch.algolia.com/apply/
and some configuration. If not then my above solution should be good enough.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
IMO a local search is way better than depending on some cloud service, so I think you did the perfect thing here :)

**Comment by jacogr** [comment]
Have not taken a look, but do agree with Shawn here on the intent.

Could you just merge master to get the yarn.lock conflict sorted and I'll take a peek.

**Comment by SaltyCucumber** [comment]
> Could you just merge master to get the yarn.lock conflict sorted and I'll take a peek.

Done

**Comment by shawntabrizi** [comment]
@jacogr tried this locally and works well. hope you don't mind the merge

**Pull request merged**
